### ISSUE TITLE
change the function that calculate the number of items in pagination system

### ISSUE THREAD

**Issue by pirosoft** [joomla-framework/database#102]
When i have many records the Model system call in libraries/src/MVC/Model/ListModel.php the function getTotal() and this call _getListQuery(), this use the getListQuery() in my component model, remove all limit and make a `count(*)` of all possible records, so the library can calculate the number of pages.
But if in my model in getListQuery() it's a query with many join, the query that keep the first 20 items (for example) is not a problem, the problem is the **count(*)** for all records for the pagination.
So the performances are terrible if the items are so many and even the joins.

My solution is add a function in **libraries/src/MVC/Model/ListModel.php**:

protected function _getPaginationListQuery() {
        static $lastStoreId;
        $currentStoreId = $this->getStoreId();

        if ($lastStoreId != $currentStoreId || empty($this->query)) {
            $lastStoreId = $currentStoreId;
            if (method_exists($this, "getListPaginationQuery")) {
                $this->query = $this->getListPaginationQuery();
            } else {
                $this->query = $this->getListQuery();
            }
        }
        return $this->query;
    }

and change the getTotal in:
public function getTotal() {
        // Get a storage key.
        $store = $this->getStoreId('getTotal');

        // Try to load the data from internal storage.
        if (isset($this->cache[$store])) {
            return $this->cache[$store];
        }

        try {
            // Load the total and add the total to the internal cache.
            $this->cache[$store] = (int) $this->_getListCount($this->**_getPaginationListQuery()**);
        } catch (\RuntimeException $e) {
            $this->setError($e->getMessage());

            return false;
        }

        return $this->cache[$store];
    }

So i can add in my model the function **getListPaginationQuery()** and insert another query without join or other options that increase the complexity of the same query.
The query in getListPaginationQuery() give the same count of items, but it's best for performance.
(I remove all the Left Join for example or some columns).
If not exist getListPaginationQuery() the library use the standard getListQuery() in component model.

Can this be insert in the next release? thanks.

**Comment by mbabker** [comment]
This logic is in the CMS' MVC implementation, if there is still a need for this an issue should be opened there.
