### ISSUE TITLE
DatabaseDriver function `__call()` docblock has wrong return type

### ISSUE THREAD

**Issue by photodude** [joomla-framework/database#107]
### Steps to reproduce the issue
the [DatabaseDriver function `__call()`](https://github.com/joomla-framework/database/blob/master/src/DatabaseDriver.php#L440-L467) docblock return type says 
```php
// @return  string  The aliased method's return value or null.
```

The type indicated here is `string` 

but the comment indicates the type could be `null`

Additionally, if there are no arguments passed we have a condition returning `void`
[see lines 452-455](https://github.com/joomla-framework/database/blob/master/src/DatabaseDriver.php#L452-L455)

### Expected result
return type should not error on Travis

### Actual result
Function return type is not void, but the function is returning void on line 454

### Additional comments

The return type should be adjusted to reflect the correct return type. 

Offhand I'm not sure if the docblock comment should be changed to
```php
// @return  string|null|void  The aliased method's return value or null.
```
or if the return on line 454 should be specified `null` with the docblock comment changed to
```php
// @return  string|null  The aliased method's return value or null.
```

Please advise for PR to correct this issue

**Comment by mbabker** [comment]
Just do `@return  mixed` because that is technically the correct return type for a magic `__call()` method.

**Comment by photodude** [comment]
close via PR #108
