### ISSUE TITLE
Need consistent syntax for parameterized query support

### ISSUE THREAD

**Issue by mbabker** [joomla-framework/database#112]
Starting with the 1.5.0 tag, all drivers have support for prepared statements and parameterized queries, and in 2.0 this will be a hard requirement because of the new `QueryInterface` dictating it.  However, the current implementation is dependent on the syntax(es) supported by the underlying driver, meaning at the moment it isn't possible to actually write "properly" abstract queries with parameterized query support (unless an application is only supporting PDO + MySQLi)

- Question mark syntax (`INSERT INTO foo (col1, col2) VALUES (?, ?)`) is supported by PDO, MySQLi, and SQL Server
- Named parameter syntax (`INSERT INTO foo (col1, col2) VALUES (:col1, :col2)`) is supported by PDO
- "PHP variable" syntax (`INSERT INTO foo (col1, col2) VALUES ($1, $2)`) is supported by PostgreSQL (`ext/pgsql`, separate from the PDO driver)

So in essence we need some kind of SQL parsing handler in the `DatabaseQuery` class.  My thought was to have it support the question mark syntax as that one is already supported by most drivers and we only need a PostgreSQL implementation.  While discussing in chat @nibra suggested we standardize around the named parameter syntax since it creates an easier to read and parse string.

Whatever the end result, we do need a solution that allows users of our API to not be concerned with these driver specific details (it's OK for now if you're writing single database applications, but because the CMS is using this package in 4.0, it becomes a problem).

**Comment by IsaacWG** [comment]
I much prefer the named parameter syntax myself. I agree with it being easier to read. I do NOT like the "PHP Varible" syntax as that could get confused with actual PHP varibles and would become a problem if a developer uses a doublequoted string instead of single quotes.

**Comment by mbabker** [comment]
To be honest I wouldn't even consider that an option, but since that's the syntax `ext/pgsql` uses I put it in here in part to demonstrate what all exists from a practical perspective and to demonstrate why we need the parser layer.

**Comment by nibra** [comment]
IMHO we should prefer the named parameter syntax, because
a) it is easier to read (fx. find an unwanted swap of parameters) and
b) it is easier to parse.
The specific driver can then convert that internally to any bespoke syntax, if needed.

**Comment by drmmr763** [comment]
I agree with @nibra - named parameters are generally easier to debug. Especially because moving to named params makes "copy / paste and run this sql directly" a pain for devs not used to it. 

A few things i've ran into writing some libraries are:
* reused named parameters in a single sql statement. I think Doctrine handles this with randomly generated variables.
* parameter types with PDO can cause some issues, especially with string / integers. Paramtypes have to get cast with predefined constants (http://php.net/manual/en/pdo.constants.php)

Finally, back to my first comment, a debug mode / tool which allows for the query to be generated in pure sql is something I'm always pining away for in Doctrine.

**Comment by mbabker** [comment]
Doctrine's [`SQLParserUtils`](https://github.com/doctrine/dbal/blob/master/lib/Doctrine/DBAL/SQLParserUtils.php) should help with this.  However, as they don't support native `ext/pgsql` their parser doesn't support converting query strings to the right syntax.

**Comment by alikon** [comment]
i'm aware this matter deserve a  more and more proof opinion,  blame me if 'im quite too naive, but for my experience  we should use  `?`

**Comment by mbabker** [comment]
If we use `?` as the syntax that'll be quickest because we ONLY have to write a parsing layer for `PostgresqlQuery` (the one used for the native `ext/pgsql` PHP extension) as every other driver supports positional parameters identified as question marks already.

If we use named parameters (`:foo`) then we have to write a parsing layer for `MysqliQuery`, `PostgresqlQuery`, and `SqlsrvQuery` because only PDO supports named parameters.

```sql
SELECT * FROM content WHERE introtext LIKE :foo OR fulltext LIKE :foo;
SELECT * FROM content WHERE introtext LIKE ? OR fulltext LIKE ?;
```

With question marks, you have to remember to put everything in the right order:

```php
$query->select('*')
    ->from('content')
    ->where('introtext LIKE ?')
    ->orWhere('fulltext LIKE ?')
    ->bind(1, '%' . $text . '%')
    ->bind(2, '%' . $text . '%');
```

With named parameters, not so much, but then you have to keep an appropriate parameter count to get things in the right order for the drivers that aren't natively named parameter compatible:

```php
$query->select('*')
    ->from('content')
    ->where('introtext LIKE :text')
    ->orWhere('fulltext LIKE :text')
    ->bind(':text', '%' . $text . '%');
```

**Comment by alikon** [comment]
> With question marks, you have to remember to put everything in the right order

i know,  if you have to deal with different db's, this is quite a normal task, as usual for different db's related things, you need to make a choice
trade off/  compromise,  there is not a perfect solution, sometimes standards is only a dream

**Comment by mbabker** [comment]
As far as the string parsing goes we can do both (look at Doctrine's parser I linked earlier).  IMO the harder part is going to be making sure we get the `$query->bind()` calls right (especially as it relates to things that have to be in numerical key sequence, i.e. any non-PDO driver).

**Comment by alikon** [comment]
i'm lazy, but i hate whatever ORM, so forgive in advance....
as usual you are hitting  the main point, i don't know wich is the better solution for ....

**Comment by alikon** [comment]
`ubi major minor cessat` ?

**Comment by nibra** [comment]
Am 20.04.2018 um 22:13 schrieb Michael Babker:

> With question marks, you have to remember to put everything in the right order:
> 
> ```php
> $query->select('*')
>     ->from('content')
>     ->where('introtext LIKE ?')
>     ->orWhere('fulltext LIKE ?')
>     ->bind(1, '%' . $text . '%')
>     ->bind(2, '%' . $text . '%');
> ```

This can get a nightmare very fast. Messing up with the order happens
very easily.

> With named parameters, not so much, but then you have to keep an appropriate parameter count to get things in the right order for the drivers that aren't natively named parameter compatible:
> 
> ```php
> $query->select('*')
>     ->from('content')
>     ->where('introtext LIKE :text')
>     ->orWhere('fulltext LIKE :text')
>     ->bind(':text', '%' . $text . '%');
> ```

I consider that being the lesser problem.

**Comment by nibra** [comment]
I'm considering to take this...

Question about the scope:
Do you just want the QueryBuilder to produce the right (S)QL for any supported DBMS? Or do you expect to be able to provide literal SQL as well?

**Comment by mbabker** [comment]
When `DatabaseQuery::__toString()` is run it should return a query that can be used by `DatabaseDriver::execute()`, in these cases it would mean replacing whatever parameter notation is used for portability with the syntax required for the underlying PHP extension.  So it just needs to produces the right SQL for the DBMS that the particular subclass represents, I don't see a reason it needs to go so far as replace parameterized arguments with literal values (although there is probably a need for such a tool, especially if you have the CMS' debug mode enabled and are looking at the executed database queries).

**Comment by csthomas** [comment]
Additional to `bind()`, could be nice to have https://www.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/query-builder.html#binding-parameters-to-placeholders

**Comment by mbabker** [comment]
Well, after https://github.com/joomla-framework/database/commit/11ab90071c65666cb2a5f6a7dc974281259ece0d this is actually a lot easier.  All the drivers now support positional parameters (`?`), so really this is now a much lower priority and it would just be a layer to map named parameters to positional parameters for drivers not supporting that.

**Comment by mbabker** [comment]
Just need something for SQL Server now (though low priority compared to anything else right now since we aren't using the driver in our applications).
