### ISSUE TITLE
Deprecate Oracle Driver

### ISSUE THREAD

**Issue by mbabker** [joomla-framework/database#121]
The `pdo_oci` extension is [largely abandonware](https://github.com/php/php-src/commits/master/ext/pdo_oci) and even Doctrine screams about [not using it](https://github.com/doctrine/dbal/blob/e4af109a206352e27c1ddab0d438c8e5f3a80d1c/lib/Doctrine/DBAL/Driver/PDOOracle/Driver.php#L27-L32).  Therefore I suggest deprecation and removal in 2.0.

**Comment by alikon** [comment]
>  PDO Oracle is not maintained by Oracle or anyone in the PHP community

not more not less

**Comment by rdeutz** [comment]
+1 on remove
