### ISSUE TITLE
[2.0] NULL Date check is inconsistent

### ISSUE THREAD

**Issue by roland-d** [joomla-framework/database#135]
### Steps to reproduce the issue
1. Install Joomla 4 on MySQL 5.7
2. Login to the administrator section
3. The control panel is empty
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/359377/43512805-63f7a68e-957c-11e8-9664-8680840b250b.png">

### Expected result
The full control panel with modules is shown.

### Actual result
The control panel has no modules.

### System information (as much as possible)
PHP 7.2.8
MySQL 5.7.22
Client API library version | mysqlnd 5.0.12-dev - 20150407
Joomla 4

### Additional comments

The query executed is
```
SELECT m.id, m.title, m.module, m.position, m.content, m.showtitle, m.params, mm.menuid

  FROM ila8e_modules AS m

  LEFT JOIN ila8e_modules_menu AS mm 
  ON mm.moduleid = m.id

  LEFT JOIN ila8e_extensions AS e 
  ON e.element = m.module 
  AND e.client_id = m.client_id

  WHERE m.published = 1 
  AND e.enabled = 1 
  AND (m.publish_up = '0000-00-00 00:00:00' OR m.publish_up <= '2018-08-01 09:13:47') 
  AND (m.publish_down = '0000-00-00 00:00:00' OR m.publish_down >= '2018-08-01 09:13:47') 
  AND m.access IN (1,1,2,3,6) 
  AND m.client_id = 1 
  AND (mm.menuid = 0 OR mm.menuid <= 0)

  ORDER BY m.position, m.ordering
```

In the database the NULL date value is `1000-01-01 00:00:00` but as you can see the query uses `0000-00-00 00:00:00`.

In this file ( https://github.com/joomla-framework/database/blob/2.0-dev/src/Mysqli/MysqliDriver.php#L930 ) the `getNullDate()` checks for the `NO_ZERO_DATE` SQL Mode. Running the query `SELECT @@SESSION.sql_mode;` through Joomla/PHP returns 
```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
``` 
however, running the same query on Sequel Pro or the MySQL CLI it returns 
```
ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

Notice that the `NO_ZERO_DATE` is there when checking directly on MySQL or using a different client but *not* when using Joomla/PHP.

I believe we need an additional check here.

**Comment by mbabker** [comment]
The modes being different between platforms means nothing.  Joomla overloads the platform defined modes (see [here](https://github.com/joomla-framework/database/blob/ac02265f2afa271eec1b146198c9baba8a3c6397/src/Mysqli/MysqliDriver.php#L89-L99) for MySQLi) for its connections, so the `0000-00-00 00:00:00` dates will work with the Joomla API by default because of that configuration.

**Comment by roland-d** [comment]
@mbabker I missed the mode overrides. Regardless, I can't run Joomla 4 on MySQL 5.7 because the getNullDate() returns the wrong value.

**Comment by mbabker** [comment]
How are you seeding the database?  I run MySQL 5.7 local and it works fine when I use the Joomla installer.  If I start trying to change content in the database through Sequel Pro that's when everything goes to hell in a hand basket, especially because of the null date issue.

The more appropriate solution for the CMS is going to be altering the database schema to `DEFAULT NULL` on date/time related columns versus trying to use a "null date", especially because of the MySQL behavioral differences with the `NO_ZERO_DATE` mode.

**Comment by roland-d** [comment]
> How are you seeding the database?

I run the Joomla installer and that works fine because the PHP client seems to have no problem inserting invalid values into the database.

```
If I start trying to change content in the database through Sequel Pro that's when everything goes to hell in a hand basket, especially because of the null date issue.
```
Yes, this also happens using HeidiSQL on Windows.

So when I change the date to a valid date for that MySQL version `1000-01-01 00:00:00` that is when Joomla won't load the modules because of the SQL query being invalid. I agree, it is a manual action after installing.

> The more appropriate solution for the CMS is going to be altering the database schema to DEFAULT NULL on date/time related columns versus trying to use a "null date",

Yes, agree with that. That is more than just replacing all the 0000-00-00 to NULL and update the schema and queries I am afraid.

Let's see perhaps I can give it a shot.

**Comment by csthomas** [comment]
Many sql queries in J4 should be changed to apply the new method `$query->isNullDatetime('publish_up')` from https://github.com/joomla-framework/database/pull/118

**Comment by roland-d** [comment]
Ok, since we have a new way to go I will close this. Thanks.
