### ISSUE TITLE
Deprecation warning for interfaces

### ISSUE THREAD

**Issue by HLeithner** [joomla-framework/database#160]
We deprecate PreparableInterface and LimitableInterface in 2.0 and trigger 2 E_USER_DEPRECATED on each request.

From performance pov it's not optimal especially as this call is prefixed with @ (Warning suppression). And the CMS will use this several years and can't switch to 3.0 until J5.0.

Can we remove the interface from QueryInterface and merge the function into QueryInterface?

I ask because I want to create a trait to the PreparableInterface but I'm not sure if this is useful if it get removed in 3.0.

**Comment by mbabker** [comment]
What you're suggesting isn't possible without B/C breaks.  In the 1.x code, the two feature interfaces are optional and in 2.x those have been made mandatory.  Moving their methods into the main query interface and removing the feature interfaces from the stack is a B/C break in that anything doing instanceof type checks will no longer work.

Yes, it gets triggered on each request, but it is a single call when the files are first loaded; it's not like those deprecation errors are being emitted once each time a query object is being created.

**Comment by HLeithner** [comment]
Yeah I already thought about this, so would you suggest to create a trait or write it directly into the databasequery class?

**Comment by mbabker** [comment]
Does anything really need a trait?  Everything that can be inlined as part of the main query class is already inlined and everything that's driver specific is in the driver subclasses.  There isn't much else you can do without doing a hard B/C break of deprecating the interfaces on 1.x and dropping them in full on 2.0, which I personally don't see there being a huge benefit in.

**Comment by HLeithner** [comment]
ok then inline ;-) thx
