### ISSUE TITLE
Suggestion: Incorporate Doctrine DBAL in V2

### ISSUE THREAD

**Issue by photodude** [joomla-framework/database#18]
As per the [Framework roadmap](http://developer.joomla.org/news/603-framework-v2-roadmap.html) "For version 2, we are looking at ... potentially consuming a third party database system." 

I don't know what has been discussed so far, but  [Doctrine DBAL](https://github.com/doctrine/dbal) seems like it might be a good candidate for consideration as it is an "Abstraction layer and access library for relational databases. A thin layer on top of PDO with a lot of additional, horizontal functionality."
- It has a larger list of [supported databases](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/platforms.html) than the current framework.
- It has the desired ability to [manage database schemas](http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/schema-manager.html)

**Comment by ianmacl** [comment]
That isn't a bad idea.  What I wonder is what value we could add to it that wouldn't make sense to contribute directly to Doctrine (i.e. what would go in our package vs. what would be just Doctrine), and whether it makes sense to morph the Database package into a Doctrine wrapper or is it better to create a new package (called ORM maybe?)?

I would suggest looking at two options:
1. Deprecate the Database package and create a new Package called ORM that wraps Doctrine
2. Deprecate the Database package and recommend developers use Doctrine directly

**Comment by mbabker** [comment]
At the Framework level, *MAYBE* our importer/exporter classes have some value (I don't know if Doctrine has something similar), but the main driver/query APIs are definitely covered in their DBAL code.  Considering we don't have a real coupling to the database in the packages, it isn't a major pain to deprecate the full database package in favor of Doctrine.

For the CMS though, if we want it building off a future version of the Framework, there will probably need to be some sort of compatibility layer.  So would it be useful to have that layer in the Framework as a transition or leave it to downstream consumers to figure out what to do?  (There's also nothing that says the CMS has to shift to Doctrine and just keeps the database package as is for itself)

**Comment by photodude** [comment]
I think I lean towards Deprecating the Database package and creating a new Package called ORM that wraps Doctrine DBAL. (I did a quick search, I didn't find any importer/exporter classes in Doctrine)

For the CMS, I hope (expect) that future builds will continue to be based on the Framework. I think an ORM compatibility layer with Doctrine DBAL that replaces the existing Database package would be appealing and an advantage to downstream consumers and the CMS.

**Comment by photodude** [comment]
I still think this is a worthwhile project

**Comment by mbabker** [comment]
I think we need to look more at specific features versus just consuming their package as a whole and dropping our's.  Especially after rebasing the CMS to actually use this repo and putting a lot of work in to get some of the features that Doctrine makes available in front of PDO.  So, let's log feature specific items instead of trying to figure out how we deprecate this package because I just don't see that being a viable option.
