### ISSUE TITLE
Query monitor should also accept the bound params

### ISSUE THREAD

**Issue by Fedik** [joomla-framework/database#214]
Joomla issue https://github.com/joomla/joomla-cms/issues/30318

Currently Query monitor logs only query string. 
https://github.com/joomla-framework/database/blob/4cda5d73eb55ac8a596f261aac08a33d658421fb/src/QueryMonitorInterface.php#L26-L28

But it also should be able to log bound params. Something like:

```php
public function startQuery(string $sql, array $params = []): void
```

**Comment by wilsonge** [comment]
Makes sense to me. Possibly we need a flag as to whether we actually are using a bound query or not

**Comment by Fedik** [comment]
As the flag may be `null` or `[array with params]` :wink: 
I tried there #215
