### ISSUE TITLE
Upmerge of recently merged PRs from master to 2.0-dev

### ISSUE THREAD

**Issue by richard67** [joomla-framework/database#221]
### Steps to reproduce the issue

Check if the 2.0-dev branch contains the changes from following PRs: #217 , #219 , #220 .

### Expected result

It does.

### Actual result

It doesn't.

### System information (as much as possible)

Not relevant here.

### Additional comments

It seems to be a while ago when the 2.0-dev branch was updated with changes from the master branch.

**Comment by nibra** [comment]
Done.

**Comment by richard67** [comment]
@nibra Hmm, I just see that the 4.0-dev branch of the CMS points to "~2.0@beta" in its composer.json, i.e. it would need to make a new 2.0 beta here before the changes can be pulled into the CMS. Or we change the CMS back from beta to 2.0-dev branch, any tag.

**Comment by nibra** [comment]
The latter makes more sense, IMHO. I'm still working on making the build process work (hasn't been green for about a year). @wilsonge, what do you think?

**Comment by richard67** [comment]
IMHO the first variant, a 2 beta-2 here, would make more sense.

**Comment by nibra** [comment]
That will take some time until I'm through with the cleanup in the framework before a new beta is meaningful.

**Comment by richard67** [comment]
Well, it's not urgent, so maybe we just wait for that, as long as it comes before 4.0 RC of the CMS.
