### ISSUE TITLE
The MySQL version check for integer display widths modifier support is not accurate enough

### ISSUE THREAD

**Issue by richard67** [joomla-framework/database#241]
### Steps to reproduce the issue

The following and possibly more changes might not be sufficient regarding the version check:

https://github.com/joomla-framework/database/commit/073aff4cde74bdd8f2db65c520610239d0a9ed43#diff-3e927448d9eaafa620c1a995e71ad8d5ab1cae1e56ef4b6a2bd78d68a430ae56R306

https://github.com/joomla-framework/database/commit/ab96e2a196a64cb99254e52a835a7d06c2f8d26f#diff-45e47bfc8339fb2db89de46a41ff0b70379e2b570c44ca9685899d898deb099cR317

MySQL who obviously don't use semver (at least not for 8.0.x) have deprecated the display width modifier beginning with version 8.0.17, see https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html .

I remember from past when I had discovered that after my MSQL had been updated so I had to make PR https://github.com/joomla/joomla-cms/pull/28501 , the display width modifier was part of the type on the 8.0.x version I had before that update.

That means the version check here should be done against version 8.0.17, and that can't be done with a floating point type cast and comparison, it needs to use something like VERSION_COMPARE for that.

Furthermore, MariaDB still support the display width modifier and so behaves like a MySQL < 8.0.17 regarding this. The version check should check this, too.

=> Ping @nibra .

**Comment by richard67** [comment]
I could make a PR to fix it, but I'd use VERSION_COMPARE for that and not cast to float, but I don't know if the use of VERSION_COMPARE is maybe not desired here.

**Comment by nibra** [comment]
VERSION_COMPARE is the better choice, no specific reason against it. The current implementation was chosen for brevity only. So please go ahead!

**Comment by richard67** [comment]
ok, will work on it.

**Comment by richard67** [comment]
I will maybe make a PR with more changes, e.g. removal of display widths from SQL scripts and statements like I do it with my 3 open PR's for the CMS. I have here a MySQL 5.7, a MySQL 8.0.20 and 2 versions of MariaDB for testing, and I want to achieve that we can run the database unit tests on all these.

If things in the 2.0-dev branch here look very different, I might make a separate PR for that branch.

**Comment by richard67** [comment]
Or maybe I keep things separate and make separate PR's for this issue here and the other changes.

**Comment by richard67** [comment]
Closing as having a pull request.
