### ISSUE TITLE
Interest in aware interface and trait

### ISSUE THREAD

**Issue by laoneo** [joomla-framework/database#261]
Is there any interest to introduce an aware interface and trait for the database as we have in [core already](https://github.com/joomla/joomla-cms/blob/4.1-dev/libraries/src/MVC/Model/DatabaseAwareTrait.php)? It would be similar to the one in the [DI package](https://github.com/joomla-framework/di/blob/2.0-dev/src/ContainerAwareInterface.php).

**Comment by laoneo** [comment]
I would do it as part of https://github.com/joomla/joomla-cms/pull/37095.

**Comment by nibra** [comment]
No objections from my side.

**Comment by laoneo** [comment]
Closing as we have a pr https://github.com/joomla-framework/database/pull/262.
