### ISSUE TITLE
Exporting all tables in zip results in one file with one table in it instead of all tables

### ISSUE THREAD

**Issue by Haran** [joomla-framework/database#298]
### Steps to reproduce the issue

1. Have regular joomla database and installation
2. Run `php cli/joomla.php database:export --folder ./tmp --zip`
3. Assert it succeeds 

### Expected result

1. Have a file `./tmp/data_exported_<TIMESTAMP>.zip`
2. File `./tmp/data_exported_<TIMESTAMP>.zip` contains **all** exported tables

### Actual result

File `./tmp/data_exported_<TIMESTAMP>.zip` contains only one (jos_workflows.xml) table, the last one

### System information (as much as possible)

Joomla! 5.0.3
```
"name": "joomla/database",
"version": "3.0.0",
"version_normalized": "3.0.0.0",
```

### Additional comments

This happens because ExportCommand creates one zip file over `foreach ($tables as $table)`

**Comment by richard67** [comment]
@rdeutz Can't this issue be closed now as the corresponding PR #299 has been merged?

P.S.: I would close it myself but as you have added the "bug" label here after having merged the PR I thought maybe that has a reason, that's why I ask.

**Comment by richard67** [comment]
@rdeutz I just see I do not have the privileges in this repo to close this issue.

**Comment by Hackwar** [comment]
As Richard wrote, the PR is merged, so I'm closing this ticket.
