### ISSUE TITLE
database model

### ISSUE THREAD

**Issue by Marion04** [joomla-framework/database#34]
As a database specialist I sometimes manipulate data directly in the joomla database. Every time I do so, I'm frustrated by the joomla data model. It is complex, redundant, allows invalid data. It looks like a datamodel which hasn't been built by concept, but grown wildly. 
I'm sure programming (and data management) would be much easier and less buggy with a proper data model. 
I suggest to bring several database specialists together in order to simplyfy the joomla data model for the next major release. I'm ready to work in such a group if I'm needed.

**Comment by nibra** [comment]
You're right - the database needs an overhaul. For Joomla 3.x there's not much chance to change that, but in Joomla 4, we can do it right. So your input is appreciated!

**Comment by anibalsanchez** [comment]
Database model needs a review from historical perspective. It is a model that has been in use for 10 years.

However, most hostings are running on MySQL 5.1 - 5.5. I would not add hard restrictions, like enforced FK or advanced MySQL configurations.... additionally there are many NoSQL fans.

**Comment by nibra** [comment]
In J!4, we'll use an external DB abstraction layer (Doctrine) with our own ORM. The latter will be capable of serving any storage technology (filesystem, web services, relational and non-relational databases). The segregation of read and write access enables us to provide de-normalized NoSQL read sources, while write access still goes to a relational, fully normalized database.

**Comment by anibalsanchez** [comment]
In JWC15 - Joomla 4 Architecture, Chris mentioned Doctrine DBAL (similar to JDatabaseQuery) for a smooth transition beetwen Joomla 3-4-5.... not a full ORM.

**Comment by nibra** [comment]
That's why I said " external *DB abstraction layer* (Doctrine) with *our own* ORM".

**Comment by anibalsanchez** [comment]
My impression is that Joomla is not going to bundle a Joomla "ORM" with object-relational mapping between model and mysql: transparent persistence, type inference, 1:N and N:N associations, multi-valued attributes, etc. 

Just the usual model-query translation on Doctrine DBAL.

**Comment by nibra** [comment]
The goal is to remove the persistence model away from the business model. Building queries would make that impossible, because SQL would be involved.

**Comment by Marion04** [comment]
Who's the person to address to get information on the existing data model and to offer my services for the data model for Joomla 4 Architecture?

**Comment by nibra** [comment]
We haven't touched the data structure yet. It is planned to normalise the structure, according to moving functionality to horizontal components.
For the latter, it is Marco Dings (PLT), who is the leader of the Joomla!4 Working Group.

**Comment by photodude** [comment]
Some of this is included in issue #18 There are definitely a wide range of opinions on this topic.

**Comment by mbabker** [comment]
Closing out this specific item.  This repo is focused in solely on the actual database abstraction layer and not really on any particular application's data model (or even ORM capabilities).  Still a lot to do but progress has been made over the years, other issues can be raised either on the CMS repo for the actual data model in that app or for more specific items regarding the API here.
