### ISSUE TITLE
Query implementing PreparableInterface throws Exception

### ISSUE THREAD

**Issue by jbanety** [joomla-framework/database#46]
I'm using the `MysqliDriver::lockTable()` method.

With the commits of recent days (nearly https://github.com/joomla-framework/database/commit/382f9cbddaade4c06e02392f234c7f7045752f25), this method throws an exception with this message : "This command is not supported in the prepared statement protocol yet.".

I'm using MariaDB server (I don't know if it is important).
Imo, the `LOCK TABLES` statement cannot be prepared.

**Comment by mbabker** [comment]
Probably need to have that method use `executeTransactionQuery()` internally (and probably rename that method before tagging a stable release to something more generic).

**Comment by jbanety** [comment]
My PR #47 does the trick but I didn't go further in investigation.
