### ISSUE TITLE
`mysqli_stmt::get_result()` is not available on HHVM

### ISSUE THREAD

**Issue by photodude** [joomla-framework/database#63]
### Steps to reproduce the issue
Review Travis HHVM tests, `mysqli_stmt::get_result()` is not available on HHVM

### Expected result
no error

### Actual result
```php
Fatal error: Call to undefined method mysqli_stmt::get_result() in /src/Mysqli/MysqliDriver.php on line 635
```

### System information (as much as possible)
HHVM 3.15.3

### Additional comments
HHVM won't fix this but would take a PR to add the functionality
https://github.com/facebook/hhvm/issues/2368

As such we have 3 options
1. Explicitly drop HHVM support
2. Submit a PR to HHVM to add the functionality
3. Rewrite the portion of the driver to iterate/loop over the results and return all of the results.

**Comment by mbabker** [comment]
HHVM has never been supported.  We've tested against it on the Framework packages since it's easy to do with Travis-CI but I don't think we have any HHVM specific workarounds in place and we have definitely not made a support statement.  So honestly, I consider it low priority (if any) to do something about this.  Even other large projects in the PHP ecosystem are now coming back around questioning their HHVM support versus aiming to support it.

**Comment by photodude** [comment]
I'm not exactly surprised that projects are reconsidering their support or even testing against HHVM. HHVM has had a bad history of complying with existing php 5/7 behaviors. It's getting much better, it's even somewhat reasonable to run php code on hhvm since the 3.15.3 release. But there is still a long way for HHVM to go to fix all of their php 5/7 compatibility issues (compounded by the php 7.1 changes). HHVM also prioritizes things necessary for their projects leaving critical issues in the code that blocks support (or even blocks just testing) For example this issue with `mysqli_stmt::get_result()` it's a support/testing blocker and HHVM has suggested they won't fix it, but will let others fix it (and no one has stepped forward to implement a fix).

Then there is the additional issue of HHVM unit tests often running significantly slower on Travis CI due to the non-container necessity (hopefully fixed with the release of the trusty containers at the end of 1Q17) and sometimes due to the HHVM JIT (since JIT is usually bad for short-lived code like unit tests). and those testing against the current precise containers on travis are testing against the majorly outdated 3.6 EOL version of HHVM

I agree this is a low priority issue.
Like I said there are 3 options to consider, I have seen some projects like the CleverStyle-Framework [implement something that eliminates the `mysqli_stmt::get_result()` function](https://github.com/nazar-pc/CleverStyle-Framework/commit/d85564df13c20762218abcdd11eb2e9f70cd6ab4) and the dependency on the MySQL Native Driver PHP extension, ext/mysqlnd (which HHVM does not currently have)

Still a low priority issue (especially since there are still major issues in the PostgreSQL driver in the framework)

**Comment by photodude** [comment]
closing as Joomla cms, Laravel, Symfony, Doctrine, CakePHP, MongoDB, PHPUnit, Composer, Twig, Silex, and Swiftmailer, etc have all dropped support for HHVM (that is something like 75% of the php market use has dropped support).
