### ISSUE TITLE
add Oracle CI testing

### ISSUE THREAD

**Issue by photodude** [joomla-framework/database#73]
### Steps to reproduce the issue
no continuous integration testing is currently performed on some database platforms like Oracle, etc

### Expected result
Test against all our database platforms like Oracle, etc

### Actual result
no continuous integration testing is currently performed of the Oracle driver

### Additional comments
Apparently, someone has a workaround for testing Oracle DB on travis ci as well https://github.com/cbandy/travis-oracle

an Oracle account is required and the Oracle username and password has to be in the build environment variables either as hidden repository settings or encrypted variables

**Comment by photodude** [comment]
Another [option for Oracle](https://continuousphp.com/documentation/databases/oracle/) is @continuousphp Doctrine is working on implementing Oracle testing on the DBAL package. 

https://continuousphp.com

Setup is all done in the account via their web interface.

**Comment by mbabker** [comment]
Oracle is dropped.
