### ISSUE TITLE
[RFC] Adopt stricter MySQL sql_mode?

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla-framework/database#91]
in Joomla 4.0 joomla used a strict sql mode
https://github.com/joomla/joomla-cms/pull/12494/files

This was reverted when joomla 4.0 was updated to use the framework database package.

As we know MySql is becoming stricter as the other database systems (postgresql, Mssql) already are.

Example:
> In MySQL 5.7.4, the ERROR_FOR_DIVISION_BY_ZERO, NO_ZERO_DATE, and NO_ZERO_IN_DATE SQL modes were changed so that they did nothing when named explicitly. Instead, their effects were included in the effects of strict SQL mode (STRICT_ALL_TABLES or STRICT_TRANS_TABLES). The intent was to reduce the number of SQL modes with an effect dependent on strict mode and make them part of strict mode itself.

> However, the change to make strict mode more strict by including ERROR_FOR_DIVISION_BY_ZERO, NO_ZERO_DATE, and NO_ZERO_IN_DATE caused some problems. For example, in MySQL 5.6 with strict mode but not NO_ZERO_DATE enabled, TIMESTAMP columns can be defined with DEFAULT '0000-00-00 00:00:00'. In MySQL 5.7.4 with the same mode settings, strict mode includes the effect of NO_ZERO_DATE and TIMESTAMP columns cannot be defined with DEFAULT '0000-00-00 00:00:00'. This causes replication of CREATE TABLE statements from 5.6 to 5.7.4 to fail if they contain such TIMESTAMP columns.

> **The long term plan is still to have the three affected modes be included in strict SQL mode and to remove them as explicit modes in a future MySQL release. But to restore compatibility in MySQL 5.7 with MySQL 5.6 strict mode and to provide additional time for affected applications to be modified**, the following changes have been made:
> [...]

See https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-8.html#mysqld-5-7-8-sql-mode

Also see discussion in https://github.com/joomla/joomla-cms/issues/16788

**Comment by mbabker** [comment]
In general we still need to port many changes from the CMS to get the Framework at a comparable level.  So I think eventually that change will land back in the code stack.

Very purposefully, we've got the CMS using all of the Framework 2.0 development branches now.  So we've got a bit of flexibility as it relates to making changes without needing strict B/C (but we should still try to be careful with that as it relates to our Framework 1.x stable line).

**Comment by andrepereiradasilva** [comment]
ok. one question: do you think it's possible for the framework accept a `sql_modes` array parameter and if that parameter exists in mysql drivers set those sql modes?

that way we don't need to hardcode sql_modes in the framework and one can add it to joomla 4.0 when creating the database driver.

**Comment by mbabker** [comment]
I don't see why not.

**Comment by andrepereiradasilva** [comment]
should be a better way right?

**Comment by andrepereiradasilva** [comment]
see https://github.com/joomla-framework/database/pull/92
